[package]
name = "bsp-simulation"
version = "0.1.0"
edition = "2021"

[dependencies]
bsp-core = { path = "../bsp-core" }
tokio = { workspace = true }
serde = { workspace = true }
anyhow = { workspace = true }
rand = "0.8"
rand_distr = "0.4"

[features]
default = []